name: pearl
on:
  workflow_dispatch:
  push:
    branches: [ main, emacs ]
  pull_request:
    branches: [ main, emacs ]
jobs:
  all:
    name: all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set env variables
      uses: ./github/env/
    - run: sudo apt-get install gcc-aarch64-linux-gnu
    - run: sudo apt-get install binutils-aarch64-linux-gnu
    - run: sudo apt-get install g++-aarch64-linux-gnu
    - run: sudo apt-get install device-tree-compiler
    - run: sudo apt-get install autopoint
    - run: sudo apt-get install lzop
    - run: sudo apt-get install libipc-run-perl
    - run: make -j3 build/stages/stage1/stage1.image
    - run: make -j3 build/stages/stage1/stage1.image.macho
    - run: make -j3 build/pearl.macho
    - run: make -j3 build/pearl.macho{artifact}
